language: c

os: linux

cache:
  directories:
    - $HOME/.stack
    - $HOME/.cabal/packages
    - $HOME/.cabal/store
    - $HOME/.ghcup

addons:
  apt:
    packages:
      - libgmp-dev

env:
  jobs:
    - EXEC="stack" RESOLVER="lts-11"
    - EXEC="stack" RESOLVER="lts-12"
    - EXEC="stack" RESOLVER="lts-14"
    - EXEC="cabal" GHC_VERSION="8.8.2"

before_install:
  - |
    case "$EXEC" in
      stack)
        mkdir -p ~/.local/bin
        export PATH="$HOME/.local/bin:$PATH"
        export STACK="stack --resolver=$RESOLVER"
        travis_retry curl -L \
          https://get.haskellstack.org/stable/linux-x86_64.tar.gz | \
          tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
        ;;
      cabal)
        mkdir -p ~/.ghcup/bin
        curl -L \
          https://gitlab.haskell.org/haskell/ghcup/raw/master/ghcup > \
          ~/.ghcup/bin/ghcup
        chmod +x ~/.ghcup/bin/ghcup
        export PATH="$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH"
        ghcup -c install-cabal
        ghcup -c install $GHC_VERSION
        ghcup -c set $GHC_VERSION
        ;;
    esac

install:
  - |
    case "$EXEC" in
      stack)
        stack --version
        $STACK update
        $STACK --no-terminal --install-ghc test --only-dependencies
        ;;
      cabal)
        which cabal
        which ghc
        cabal --version
        ghc --version
        travis_retry cabal v2-update
        ;;
    esac

script:
  - |
    case "$EXEC" in
      stack)
        $STACK --no-terminal build --fast --test --coverage \
          --no-run-tests \
          finkel-kernel finkel-setup finkel-lang p02 finkel-tool
        $STACK --no-terminal build --fast --test --coverage \
          finkel-kernel finkel-setup finkel-lang finkel-tool
        ;;
      cabal)
         cabal v2-build all
         cabal v2-test all
         cabal v2-haddock all
         ;;
    esac

after_script:
  - |
    case "$EXEC" in
      stack)
        $STACK install hpc-codecov
        HPCROOT=$($STACK path --local-hpc-root)
        DISTDIR=$($STACK path --dist-dir)
        TIX=$(find $HPCROOT -name 'all.tix')
        hpc-codecov \
          --src=kernel --mix=kernel/$DISTDIR/hpc \
          --src=setup --mix=setup/$DISTDIR/hpc \
          --src=lang --mix=lang/$DISTDIR/hpc \
          --src=tool --mix=tool/$DISTDIR/hpc \
          --out=codecov.json --verbose $TIX
        bash <(curl -s https://codecov.io/bash)
        ;;
      cabal)
        echo Not taking codecov for cabal-install yet
        ;;
    esac
