language: c

cache:
  directories:
    - $HOME/.stack
    - $HOME/.cabal/packages
    - $HOME/.cabal/store
    - $HOME/.ghcup
    - $HOME/AppData/Local/Programs/stack
    - $HOME/AppData/Roaming/stack

addons:
  apt:
    packages:
      - libgmp-dev
  homebrew:
    packages:
      - haskell-stack

    # Workaround for "Unknown command: bundle", see: https://bit.ly/32d3V2d
    update: true

os:
  - linux
  - osx
  - windows

env:
  global:
    - TMPDIR=$TRAVIS_BUILD_DIR/tmp
  jobs:
    - EXEC=stack RESOLVER=lts-11
    - EXEC=stack RESOLVER=lts-12
    - EXEC=stack RESOLVER=lts-14
    - EXEC=cabal GHC_VERSION=8.8.2

# OSX and WINDOWS are entirely excluded at the moment.
jobs:
  exclude:
    - os: osx
      env: EXEC=stack RESOLVER=lts-11
    - os: osx
      env: EXEC=stack RESOLVER=lts-12
    # - os: osx
    #   env: EXEC=stack RESOLVER=lts-14
    - os: osx
      env: EXEC=cabal GHC_VERSION=8.8.2
    - os: windows
      env: EXEC=stack RESOLVER=lts-11
    - os: windows
      env: EXEC=stack RESOLVER=lts-12
    # - os: windows
    #   env: EXEC=stack RESOLVER=lts-14
    - os: windows
      env: EXEC=cabal GHC_VERSION=8.8.2

before_install:
  - mkdir -p $TMPDIR
  - . ci/travis.sh

install:
  - travis_install

script:
  - travis_script

after_success:
  - travis_after_success
