# File: my-first-package/package.yaml

name: my-first-package
version: 0.1.0.0

extra-source-files:
  - src/**.fnk

custom-setup:
  dependencies:
    - base
    - Cabal
    - finkel-tool

library:
  source-dirs: src
  exposed-modules: MyFirstPackage
  build-tools:
    - finkel-tool:finkel
  dependencies:
    - base
